### ISSUE TITLE
code: 6100, message: '本版本内不支持的接口或者接口已经被废弃，请参考该接口的文档

### ISSUE THREAD

**Issue by dogsmall** [CFETeam/qcloudapi-sdk#2]
`var Capi = require('qcloudapi-sdk')

//通过构造函数传入的参数将作为默认配置
var capi = new Capi({
        // baseHost: 'wenzhi.api.qcloud.com',
        SecretId: 'AKID4r2cxZhSLK2Mrtlnl5k3PAACygctvfpu',
        SecretKey: '*****************************************',
        serviceType: 'account'
    })
    // 传入配置以覆盖默认项
capi.request({
    Region: 'bj',
    Action: 'TextSentiment',
    content: '我爱洗澡',
    type: 1
}, function(error, data) {
    if (error) {
        console.log(error);
    }
    console.log(data)
})`
code: 6100, message: '本版本内不支持的接口或者接口已经被废弃，请参考该接口的文档。'

**Comment by justan** [comment]
serviceType 应该是 'wenzhi'

**Comment by dogsmall** [comment]
我后来发现了，但是改了还报这个错…

**Comment by justan** [comment]
如果还有问题请帖下入参. 
PS: 修改原贴把 secretkey 处理下

**Comment by dogsmall** [comment]
`var Capi = require('qcloudapi-sdk')

//通过构造函数传入的参数将作为默认配置
var capi = new Capi({
    SecretId: 'AKID4r2cxZhSLK2Mrtlnl5k3PAACygctvfpu',
    SecretKey: '***********************************************',
    Action: 'TextSentiment',
    Region: 'bj',
    content: '我爱洗澡',
    type: 4,
    serviceType: 'wenzhi'
})
capi.request({
    Region: 'sz'
}, function(error, data) {
    if (error) {
        console.log(error);
    }
    console.log(data)
})
var qs = capi.generateQueryString({
    Region: 'bj',
    Action: 'TextSentiment'
}, {
    serviceType: 'wenzhi'
})
console.log(qs)
//Region=bj&SecretId=AKID4r2cxZhSLK2Mrtlnl5k3PAACygctvfpu&Timestamp=1464661211&Nonce=19376&RequestClient=SDK_NODEJS_0.1.4&Action=TextSentiment&Signature=KbyqbMtlbb5eYfoPS9LWrSma5ps%3D
`
报错: code: 6100, message: '请求失败，参数错误:[action]' 
我看源码里request里已经对标签之类的做了处理了,所以直接调用request应该就可以了啊,但是还是有问题

**Comment by dogsmall** [comment]
queryString 中没有 content参数和type参数

**Comment by dogsmall** [comment]
找到问题了,腾讯那面数据库服务器坏了,没有同步我额度,我这看有额度,然后一直报调用次数超出

**Comment by justan** [comment]
额. 上面的调用是有问题的. 构造函数的参数和 `.request` 方法的参数不能混为一谈的.
具体的先看下文档吧: 
https://github.com/CFETeam/qcloudapi-sdk/blob/master/api.md#new-qcloudapidefaults

**Comment by dogsmall** [comment]
恩恩,我知道,刚才我改好了还报那个调用次数超限,结果我就找客服给我查一下我的额度,结果客服说数据库服务器坏了,我昨天领的五万次没有同步到服务器,现在好了!谢了
